name: container

on:
  push:
    branches: [ main ]

jobs:
  build-container:
    runs-on: ubuntu-latest
    name: build_container
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: paulosmallz
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2

      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/wechorg/public-package3:latest
